
language: java

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - akamen@blackducksoftware.com
      - jrichard@blackducksoftware.com
      - psantos@blackducksoftware.com
      - ekerwin@blackducksoftware.com

install: true
script:
  - mvn clean package -Dmaven.test.skip=true
after_success:
  - mvn test jacoco:report coveralls:report
